"""
tasks/ml_tasks.py — Celery task for ML model training.

Wraps ml_service.train_stream() so training runs in the
celery-worker container instead of blocking the FastAPI event loop.
"""
import json as _json
from worker import celery_app
from services.ml_service import ml_service


@celery_app.task(bind=True)
def train_model_task(self, model_id: str, name: str, train_params: dict):
    """
    Run ML training in the background.

    Args:
        model_id: UUID string pre-generated by the router.
        name: Human-readable model name supplied by the user.
        train_params: Dict matching ml_service.train_stream() kwargs
                      (symbol, exchange, interval, features, model_type,
                       task, split_ratio, hyperparams, filters, lookback_steps).

    Returns:
        Dict with keys: model_id, name, metrics, feature_importance,
                        model_path, features_used, symbol, exchange,
                        model_type, task, hyperparams, filters, interval,
                        date_from, date_to.

    Raises:
        Exception: propagated from training errors so Celery marks task FAILURE.
    """
    gen = ml_service.train_stream(model_id=model_id, **train_params)

    for sse_str in gen:
        raw = sse_str.strip()
        if not raw.startswith("data: "):
            continue
        try:
            event = _json.loads(raw[6:])
        except _json.JSONDecodeError:
            continue

        etype = event.get("type")

        if etype in ("start", "progress"):
            self.update_state(state="PROGRESS", meta={"msg": event.get("msg", ""), "type": etype})

        elif etype == "epoch":
            self.update_state(state="PROGRESS", meta={
                "type": "epoch",
                "epoch": event.get("epoch"),
                "total": event.get("total"),
                "loss": event.get("loss"),
            })

        elif etype == "done":
            return {
                "model_id": model_id,
                "name": name,
                "symbol": train_params["symbol"],
                "exchange": train_params["exchange"],
                "model_type": train_params["model_type"],
                "task": train_params["task"],
                "hyperparams": train_params["hyperparams"],
                "filters": train_params["filters"],
                "interval": train_params["interval"],
                "date_from": train_params.get("date_from"),
                "date_to": train_params.get("date_to"),
                "features_used": event.get("features_used", []),
                "metrics": event.get("metrics", {}),
                "feature_importance": event.get("feature_importance", {}),
                "model_path": event.get("model_path"),
            }

        elif etype == "error":
            raise Exception(event.get("msg", "Training failed"))

    raise Exception("train_stream ended without a 'done' event")
